version: '3.8'

services:
  ai-dotnet-api-service:
    image: registry.token-ai.cn/thor:latest
    ports:
      - 18080:8080
    build:
      context: .
      dockerfile: src/Thor.Service/Dockerfile
    container_name: thor
    volumes:
      - ./data:/data
    environment:
      - TZ=Asia/Shanghai
      - DBType=sqlite # sqlite | [postgresql,pgsql] | [sqlserver,mssql] | mysql
      - ConnectionString=data source=/data/token.db
      - LoggerConnectionString=data source=/data/logger.db
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_PORTS=8080